config/routes.rb
Rails.application.routes.draw do


  # get 'logout' => 'users/sessions#destroy', :as => 'logout'
  # Rails.application.routes.draw do
    devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
    }
  # end

  # devise_for :users
  get 'comments/create'



  # post 'access/attempt_login'


  # get 'login' => 'access#login', :as => 'login'



  root 'recipes#index'

  resources :categories

  resources :recipes do
      get :new_version, on: :member
      resources :comments
  end
  resources :users

  # resources :notifications, only: [:index]
  resources :notifications do
      collection do
          post :mark_as_read
      end
  end

  get ':token', :to => 'recipes#show_shareable'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
    serialize :ingredients
    # serialize :key_words
    belongs_to :category
    belongs_to :user
    has_many :comments, dependent: :destroy # destruyo los comentarios de esta receta si la borro





    before_validation :generate_token, on: :create

    validates :token, presence: true
    validates :token, uniqueness: true



    # has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ':style/default.jpeg'
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    validates :name, :presence => true, :length => { :minimum => 3 }
    validates :ingredients, :presence => true, :length => { :minimum => 1 }
    validates :key_words, :presence => true, :length => { :minimum => 1 }
    validates :instructions, :presence => true, :length => { :minimum => 10 }

    scope :search, lambda {|query| where(["name ILIKE ? OR key_words ILIKE ?", "%#{query}%", "%#{query}%"]) } #esto es seguro! porque es saneado query
    # Package.includes(:package_size).order("package_sizes.sort_order")
    scope :sorted, -> { order("recipes.name ASC") }
    # scope :sorted, -> { order(Recipe.joins(:category).merge(Category.order(name: :asc)), name: :asc) }
    # scope :sorted, -> { joins(:category).order("category.name") }
    # scope :sorted, -> { includes(:category).order("category.name DESC") }
    # scope :sorted, -> {  }

    def generate_token
      begin
        self.token = SecureRandom.urlsafe_base64(16, false)
      end while self.class.find_by(token: token)
    end


    # def to_param
    #   token
    # end
end

app/controllers/recipes_controller.rb
# include Devise::Controllers::Helpers
class RecipesController < ApplicationController
  layout "shared", only: [:show_shareable]
  # before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:show_shareable]
  before_action :confirm_permissions, :only => [:edit, :update, :destroy]

  # def user_signed_in?
  #   !!current_user
  # end
  #
  # def current_user
  #   @current_user ||= warden.authenticate(scope: => :user)
  # end
  #
  # def user_session
  #   current_user && warden.session(:user)
  # end

  def index
      @categories = Category.sorted
      @results = {}
      if params[:search]
          # @recipes = Recipe.search(params[:search]).sorted
          @categories.each do |category|
            @results[category.name] = category.recipes.search(params[:search]).sorted
          end
      elsif params[:user]
          # @recipes = Recipe.where(:user => params[:user]).includes(:category).order("categories.name ASC").sorted
          @categories.each do |category|
            @results[category.name] = category.recipes.where(:user => params[:user]).sorted
          end
      else
          @categories.each do |category|
            @results[category.name] = category.recipes.sorted
          end
          # @recipes = Recipe.includes(:category).order("categories.name ASC").sorted
      end



  end

  def show
      @recipe = Recipe.find(params[:id])
      @comment = Comment.new
      @comments = Comment.all
  end

  def show_shareable
      # @categories = Category.all
      # @comment = Comment.new
      # @comments = Comment.all
      @recipe = Recipe.find_by :token => params[:token]
      # render(:partial => 'receta')
  end

  def new
      @category = Category.new
      @recipe = Recipe.new
  end

  def new_version
      parent = Recipe.find(params[:id])
      @recipe = Recipe.new(parent.attributes)
      @recipe.name = @recipe.name + ": version ..."
      render('new')
  end

  def create
    logger.debug("******** INGS AL CREAR ANTES SPLIT #{recipe_params[:ingredients]}***********")
    ingredients = recipe_params[:ingredients].split(',')
    logger.debug("******** INGS AL CREAR DSP SPLIT #{ingredients}***********")
    # ingredients.map!(&:strip)
    # @recipe = Recipe.new(recipe_params.merge({ingredients:ingredients}))
    # @recipe.save
    # valid_record?(@recipe, "Receta '#{@recipe.name}' creada exitosamente.", recipes_path, 'new')



    @user = helpers.current_user
    @recipe = @user.recipes.build(recipe_params.merge({ingredients:ingredients}))
    if params[:recipe][:image].blank?
           @recipe.image = nil
    end
    # @recipe.instructions = simple_format(@recipe.instructions)
    @recipe.save
    # valid_record?(@recipe, "Receta '#{@recipe.name}' creada exitosamente.", recipe_path(@recipe), 'new')
    if @recipe.valid?
      flash_redirect("Receta '#{@recipe.name}' editada exitosamente.", recipe_path(@recipe))
    else
      render('new')
    end

  end

  def edit
    @category = Category.new
    @recipe = Recipe.find(params[:id])
  end



  def update
    logger.debug("**************** INGS AL EDITAR ANTES SPLIT #{recipe_params[:ingredients]}***********")
    ingredients = recipe_params[:ingredients].split(',')
    logger.debug("**************** INGS AL EDITAR DSP SPLIT #{ingredients}***********")
    @recipe = Recipe.find(params[:id])
    @recipe.update_attributes(recipe_params.merge({ingredients:ingredients}))
    # @recipe.instructions = simple_format(@recipe.instructions)
    # valid_record?(@recipe, "Receta '#{@recipe.name}' editada exitosamente.", recipe_path(@recipe), 'edit')
    if @recipe.valid?
      flash_redirect("Receta '#{@recipe.name}' editada exitosamente.", recipe_path(@recipe))
    else
      render('edit')
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash_redirect("Receta '#{@recipe.name}' eliminada.", recipes_path)
  end


    private

    def recipe_params
      params.require(:recipe).permit(:name, :category_id, :ingredients, :key_words, :instructions, :user_id, :parent_id, :image)
    end


    def confirm_permissions
      recipe = Recipe.find(params[:id])
      unless helpers.allowed?(recipe.user)
        flash_redirect("No tenes permisos para realizar esa accion.", recipe_path(recipe))
      end
    end


end

app/helpers/recipes_helper.rb
module RecipesHelper

    def has_ingredients(recipe)
      #code
    end
end

app/views/recipes/_form.html.erb
<div class="card card-body bg-light">
<%= form_for recipe, html: { multipart: true } do |f| %>
  <%= error_messages_for(f.object) %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label "Nombre", :class => "font-weight-bold" %>
        <%= f.text_field :name, :class => 'form-control', :placeholder => 'Milanesas de Ternera' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label "Categoría", :class => "font-weight-bold" %> <%#= link_to raw("Crear Nueva"), '#', data: {toggle: "modal", target: "#modalCategory"}, :class => 'btn btn-sm btn-outline-success' %>
        <%= f.select :category_id, Category.sorted.collect { |x| [x.name, x.id] }, {:include_blank => 'Elegir Una'}, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label "Ingredientes y Cantidades", :class => "font-weight-bold" %>
        <div id="tags">
          <%= f.hidden_field :ingredients, :value => get_ingredients(recipe), :id => 'hiddenInput' %>
          <%= text_field_tag 'tagInput', nil, class: 'form-control', :placeholder => "Separa los ingredientes por coma" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label "Palabras Clave", :class => "font-weight-bold" %>
        <%= f.text_area :key_words, :class => 'form-control', :placeholder => "Ternera, Nalga", :size => '10x6' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Instrucciones", :class => "font-weight-bold" %>
    <div id="instr">
      <%= f.hidden_field :instructions, :value => recipe.instructions, :id => 'instrHidden' %>
      <%= text_area_tag 'instrInput', nil, :class => 'form-control', :size => '10x8'%>
    </div>
  </div>



  <div class="form-group">
    <%= f.label "Foto" %>
    <%= f.file_field :image %>
  </div>
  <% if recipe.image.exists? %>
     <%= image_tag recipe.image.url, :width => '100%' %>
  <% end %>

  <%= f.submit "Aceptar", :class => 'btn btn-success' %>
  <%= link_to "Cancelar", recipes_path, :class => 'btn btn-outline-danger' %>

<% end %>
</div>





<!-- <div class="modal fade" id="modalCategory" tabindex="-1" role="dialog" aria-labelledby="modalCategory" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalCategory">Creá una Nueva Categoría</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%# form_for @category do |f| %>
          <%# error_messages_for(f.object) %>
          <div class="form-group">
            <%# f.label 'Nombre' %>
            <%# f.text_field :name, :class => 'form-control' %>
          </div>
          <br/>

          <%# f.submit "Aceptar", :class => 'btn btn-primary' %>

        <%# end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Cancelar</button>
      </div>
    </div>
  </div>
</div> -->

app/views/recipes/_link_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Copia este link para poder compartir</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <input id="bar" value="<%= request.base_url+ '/' + link %>" readonly class="form-control">
      </div>
      <div class="modal-footer">
        <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
        <!-- Target -->
<!-- <input id="bar" value="<%= 'holitas' %>" readonly> -->

<!-- Trigger -->
        <button class="clipboard-btn btn btn-success" data-clipboard-action="copy" data-clipboard-target="#bar">
          <%= fa_icon "clipboard" %> Copiar!
        </button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

app/views/recipes/_receta.html.erb
<% @page_title = @recipe.name %>

<!-- <div class="container"> -->

        <div class="jumbotron text-center">
            <h1 class="nombre-receta"><%= @recipe.name %></h1>
            <h3 class="categoria"><%= @recipe.category.name %></h3>
        </div>
    <ul class="ingredient">
        <% @recipe.ingredients.each do |ingredient| %>
        <li><%= fa_icon "cutlery " %> <%= ingredient %></li>
        <% end %>
    </ul>
    <div class="divider"></div>
    <div class="instrucciones">
        <%# simple_format(@recipe.instructions) %>
        <ol class="numbered-instrs">
        <%= sanitize(@recipe.instructions, :tags => ['li', 'strong', 'em']) %>
        </ol>
    </div>

<!-- </div> -->

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<% @page_title = 'Editar Receta' %>
<h2>Editar Receta</h2>

<%= render :partial => 'form', :locals => {:recipe => @recipe} %>

app/views/recipes/index.html.erb
<% @page_title = 'Recetas' %>

<div class="row my-3">
    <div class="col-md-12 fixed d-md-none">
      <%= render(:partial => 'partials/select_category') %>
    </div>

        <div class="col-md-9 col-12 ">
                <% @results.each do |category, recipes| %>
                <% next if recipes.empty? %>
                <h4 class="category-header mt-4"><span><%= category %></span></h4>
                <div class="card-deck">
                    <% recipes.each do |recipe| %>

                        <div class="card my-2 recipe-card">

                            <!-- <img src="http://placehold.it/560x560" class="card-img-top"> -->
                            <div class="images d-none d-sm-block">
                                <% if recipe.image? %>
                                <%= image_link_to recipe.image.url, recipe_path(recipe), :width => '100%' %>
                                <% else %>
                                    <%# image_link_to 'cutlery256x256-borde.png', recipe_path(recipe), :width => '100%'%>
                                    <%= image_link_to get_default_img, recipe_path(recipe), :width => '100%'%>

                                <% end %>
                            </div>

                            <div class="card-body">
                              <%= link_to recipe_path(recipe), :style => "text-decoration: none;" do %>
                                <h5 class="card-title"><%= recipe.name %></h5>
                              <% end %><!-- end link_to -->
                            </div>
                            <div class="card-footer">
                                <small class="recipe-info"><span class="span-footer"><%= recipe.category.name %></span><span class="font-weight-bold"> | </span><span class="span-footer font-weight-bold"><%= recipe.user.username %></span></small>
                            </div>

                        </div>

                    <% end %> <!-- recipe.each end -->

            </div> <!-- end card deck -->
            <% end %> <!-- termina results.each -->

        </div>
        <div class="col-md-3 fixed d-none d-md-block">
          <%= render(:partial => 'partials/sidebar') %>
        </div>


</div>

app/views/recipes/index0.html.erb
<% @page_title = 'Recetas' %>


<div class="row my-3">
    <div class="col-md-12 fixed d-md-none">
      <%= render(:partial => 'partials/select_category') %>
    </div>
    <div class="col-md-9 col-sm-12">
      <!-- <div class="card card-body bg-light"> -->
        <h2>Recetas</h2>
            <% @results.each do |category, recipes| %>
                <% next if recipes.empty? %>
                <h4 class="category-header"><span><%= category %></span></h4>
                <% recipes.each_slice(3) do |recipe_pair| %>

                  <div class="row">
                    <% recipe_pair.each do |recipe| %>
                      <div class="col-md-4">
                        <figure>
                          <%= link_to recipe_path(recipe), :style => "text-decoration: none;" do %>
                                <% if recipe.image.exists? %>
                                    <%= image_tag  recipe.image.url(:medium), :width => '100%'%>
                                <% else %>
                                    <%# image_link_to 'default.jpeg', recipe_path(recipe), :width => '100%'%>
                                <% end %>

                              <figcaption style="background:white; padding: 1em; text-align: center;">
                                <h5><%= recipe.name %></h5>
                                <small><%= recipe.category.name %> | <%= recipe.user.username %></small>
                              </figcaption>
                          <% end %>
                        </figure>

                      </div>
                    <% end %>
                  </div>
                <% end %>
            <% end %>


      <!-- </div> -->
    </div>
    <div class="col-md-3 fixed d-none d-md-block">
      <%= render(:partial => 'partials/sidebar') %>
    </div>
</div>

app/views/recipes/new.html.erb
<% @page_title = 'Nueva Receta' %>
<h2>Crear Nueva Receta</h2>

<%= render :partial => 'form', :locals => {:recipe => @recipe} %>

app/views/recipes/show.html.erb
<%= link_to "<< Volver Atrás", recipes_path, :class => 'btn btn-primary my-2'  %>
    <div class="card card-body bg-light">
    <%= render :partial => 'receta', :locals => {:recipe => @recipe} %>



    <div class="row">
        <div class="col-md-6 user-info"><%= render :partial => 'partials/user_date', :locals => {:user => @recipe.user, :date => @recipe.created_at} %></div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <%= link_to "Nueva Version", new_version_recipe_path(@recipe), :class => 'btn btn-blue' %>
            <%# link_to raw("Compartir <i class='fa fa-link'></i>"), '#', data: {toggle: "modal", target: "#exampleModal"}, :class => 'btn btn-outline-success' %>
            <button class="btn btn-outline-success clipboard-btn" data-clipboard-action="copy" data-clipboard-text="<%= request.base_url %>/<%= @recipe.token %>">
              Compartir <%= fa_icon "link" %>
            </button>
            <%# social_share_button_tag(@recipe.name, :url => request.base_url +  "/"+ @recipe.token) %>
            <%# link_to raw("Compartir <i class='fa fa-link'></i>"), '#', data: {clipboard_text: request.base_url + '/' + @recipe.token }, :class => 'btn btn-outline-success clipboard-btn' %>
        </div>
        <div class="col-md-6 col-sm-12 mt-2 mt-md-0">
            <% if allowed?(@recipe.user) %>
                <%= render :partial => 'partials/edit_delete', :locals => {:edit => edit_recipe_path(@recipe), :delete => recipe_path(@recipe)} %>
            <% end %>
        </div>
    </div>


<%= render :partial => 'link_modal', :locals => {:link => @recipe.token} %>
</div>
<%= render 'partials/comments' %>

app/views/recipes/show_shareable.html.erb
<div class="card card-body bg-light">
<%= render :partial => 'receta', :locals => {:recipe => @recipe} %>
</div>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>