config/routes.rb
Rails.application.routes.draw do


  # get 'logout' => 'users/sessions#destroy', :as => 'logout'
  # Rails.application.routes.draw do
    devise_for :users, controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
    }
  # end

  # devise_for :users
  get 'comments/create'



  # post 'access/attempt_login'


  # get 'login' => 'access#login', :as => 'login'



  root 'recipes#index'

  resources :categories

  resources :recipes do
      get :new_version, on: :member
      resources :comments
  end
  resources :users

  # resources :notifications, only: [:index]
  resources :notifications do
      collection do
          post :mark_as_read
      end
  end

  get ':token', :to => 'recipes#show_shareable'

end

app/views/partials/_comments.html.erb
<div class="comments">
    <h3 class="page-header"> Comentarios </h3>
    <% @recipe.comments.each do |comment| %>
    <!-- <div class="comment"> -->
        <div class="row">
            <div class="col-md-12">
                <div class="card bg-light card-body my-1 comment" id="comment_<%= comment.id %>">

                    <h4 class="card-title page-header"><%= render :partial => 'partials/user_date', :locals => {:user => comment.user, :date => comment.created_at} %></h4>
                     <div class="card-body">
                         <%= comment.body %>
                     </div>
                     <% if allowed?(comment.user) %>
                             <div class="row justify-content-md-end">
                                 <div class="col-md-2">
                                     <%= link_to recipe_comment_path(comment), :method => :delete, :class => 'btn btn-outline-danger' do %>
                                         <%= fa_icon "trash-o" %>
                                     <% end %>
                                 </div>

                            </div>
                     <% end %>
                </div>
            </div>
        </div>
    <!-- </div> -->
    <% end %>

        <div class="add-comment card card-body my-2">
            <h3 class="page-header card-title">Nuevo Comentario</h3>
            <div class="card-body">
                <%= form_for [@recipe, @recipe.comments.build] do |f| %>

                    <div class="form-group">
                        <%= f.label "Escribe aquí tu comentario" %>
                        <%= f.text_area :body, :class => 'form-control' %>
                    </div>

                    <div class="form-group">
                        <%= f.submit "Comentar", :class => 'btn btn-primary' %>
                    </div>

                <% end %>
            </div>

        </div>

</div>

app/views/partials/_edit_delete.html.erb
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to raw("<i class='fa fa-edit'></i> Cambiar"), edit, :class => 'btn btn-outline-secondary' %>
  <%= link_to delete, :method => :delete, :data => {:confirm => 'Estás seguro que querés borrar el elemento?'}, :class => 'btn btn-outline-danger' do %>
      <%= fa_icon "trash-o" %> Borrar
  <% end %>
  <%# link_to "Borrar", delete, :method => :delete, :data => {:confirm => 'Estás seguro que querés borrar el elemento?'}, :class => 'btn btn-danger' %>
</div>

app/views/partials/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div class="alert alert-danger">
      <h3>Solucionar los siguientes errores:</h3>
      <!-- <p>There were problems with the following fields:</p> -->
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/partials/_favicons.html.erb
<%= favicon_link_tag asset_path('cuchara.png'), :rel => 'icon', :type =>  'image/png' %>
<%= favicon_link_tag asset_path('favicon-32x32.png'), :rel => 'icon', :type =>  'image/png', :sizes => '32x32' %>
<%= favicon_link_tag asset_path('favicon-96x96.png'), :rel => 'icon', :type =>  'image/png', :sizes => '96x96' %>


<%= favicon_link_tag asset_path('apple-icon-57x57.png'), :rel => 'apple-touch-icon', :type =>  'image/png', :sizes => '57x57' %>
<%= favicon_link_tag asset_path('apple-icon-60x60.png'), :rel => 'apple-touch-icon', :type =>  'image/png', :sizes => '60x60' %>
<%= favicon_link_tag asset_path('apple-icon-72x72.png'), :rel => 'apple-touch-icon', :type =>  'image/png', :sizes => '72x72' %>
<%= favicon_link_tag asset_path('apple-icon-76x76.png'), :rel => 'apple-touch-icon', :type =>  'image/png', :sizes => '76x76' %>
<%= favicon_link_tag asset_path('apple-icon-114x114.png'), :rel => 'apple-touch-icon', :type =>  'image/png', :sizes => '114x114' %>
<%= favicon_link_tag asset_path('apple-icon-120x120.png'), :rel => 'apple-touch-icon', :type =>  'image/png', :sizes => '120x120' %>
<%= favicon_link_tag asset_path('apple-icon-144x144.png'), :rel => 'apple-touch-icon', :type =>  'image/png', :sizes => '144x144' %>
<%= favicon_link_tag asset_path('apple-icon-152x152.png'), :rel => 'apple-touch-icon', :type =>  'image/png', :sizes => '152x152' %>
<%= favicon_link_tag asset_path('apple-icon-180x180.png'), :rel => 'apple-touch-icon', :type =>  'image/png', :sizes => '180x180' %>
<%= favicon_link_tag asset_path('android-icon-192x192.png'), :rel => 'icon', :type =>  'image/png', :sizes => '192x192' %>


<%= favicon_link_tag asset_path('manifest.json'), :rel => 'manifest', :type => '' %>
<link href="https://fonts.googleapis.com/css?family=Roboto|Lora|Merriweather|Old+Standard+TT|Raleway" rel="stylesheet">
 <meta name="viewport" content="width=device-width, initial-scale=1">

app/views/partials/_flash.html.erb
<% if flash[:notice] %>
    <div class="flash alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
    <div class="flash alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/partials/_footer.html.erb
<footer>
  <p>Copyright &copy; 2018, rBlog | <%= admin?(controller_path) ? link_to("Frontend", root_path, :target => '_blank') : link_to("Admin Login", login_path) %></p>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar  navbar-dark navbar-toggleable-sm navbar-expand-md mx-md-5">
  <%= image_link_to "cookbook64x64.png", recipes_path, { alt: 'Ver todas las recetas' }, { class: 'navbar-brand' } %>

  <div class="collapse navbar-collapse " id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= render :partial => 'partials/search_form' %>
      </li>
    </ul>
  </div>
  <button class="navbar-toggler navbar-toggler-right mr-auto" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span><%= image_tag "menu.png" %></span>
  </button>



  <ul class=" nav ml-auto">
    <li id="favs" class="nav-item icons">
      <%= link_to '#', :class => 'nav-link' do  %>
      <span ><%= fa_icon "heart" %></span>
      <% end %>
    </li>

    <li class="nav-item dropdown icons" data-behavior="notifications">
      <a id="notif" href="" data-behavior="notifications-link" class=" nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" role="button"  id="dropdown02">
        <span ><%= fa_icon "bell" %></span>
        <span class="badge badge-pill badge-light caption" data-behavior="unread-count"></span>
      </a>
      <div id="notifications" class="dropdown-menu dropdown-menu-left" aria-labelledby="dropdown02" data-behavior="notification-items">
          <% if current_user.notifications.active.empty? %>
            <p class="small text-muted mx-2">No hay notificaciones.</p>
          <% end %>
      </div>
    </li>
  </ul>

  <ul class=" nav square-links">
    <li id="new" class="nav-item square-link">
      <%= link_to new_recipe_path, :class => 'nav-link my-2' do  %>
        <%= image_tag "knives32x32.png" %>
        <span class="caption mt-2">Nueva</span>
        <span class="caption">Receta</span>
      <% end %>
    </li>

    <li id="group" class="nav-item dropdown square-link">
      <a  class="nav-link my-2" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= image_tag "gloves32x32.png" %>
        <span class="caption mt-2">grupo</span>
        <span class="caption">nombre</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">
         <!-- <p class="dropdown-item">Hola <mark><strong><%= current_username %></strong></mark>!</p>        -->
        <%= link_to 'Categorías', categories_path, :class => 'dropdown-item' %>
        <% if current_user.admin? %>
          <% link_to 'Usuarios', users_path, :class => 'dropdown-item' %>
        <% end %>
        <%= link_to 'Mis Recetas', recipes_path(:user => current_user.id), :class => 'dropdown-item' %>
        <%= link_to 'Mi Perfil', user_path(current_user), :class => 'dropdown-item' %>
        <%# link_to 'Salir', logout_path, :class => 'dropdown-item' %>
        <%= link_to "Salir", destroy_user_session_path, :method => :delete, :class => 'dropdown-item'  %>
      </div>
    </li>

    <li id="user" class="nav-item dropdown square-link" id="user">
      <a  class="nav-link my-2" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= image_tag "chef32x32.png" %>
        <span class="caption mt-2">Tu</span>
        <span class="caption">cuenta</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">
         <!-- <p class="dropdown-item">Hola <mark><strong><%= current_username %></strong></mark>!</p>        -->
        <%= link_to 'Categorías', categories_path, :class => 'dropdown-item' %>
        <% if current_user.admin? %>
          <% link_to 'Usuarios', users_path, :class => 'dropdown-item' %>
        <% end %>
        <%= link_to 'Mis Recetas', recipes_path(:user => current_user.id), :class => 'dropdown-item' %>
        <%= link_to 'Mi Perfil', user_path(current_user), :class => 'dropdown-item' %>
        <%# link_to 'Salir', logout_path, :class => 'dropdown-item' %>
        <%= link_to "Salir", destroy_user_session_path, :method => :delete, :class => 'dropdown-item'  %>
      </div>
    </li>
  </ul>
</nav>

app/views/partials/_search_form.html.erb
<%= form_tag recipes_path, method: :get, :id =>'search-form', class: "form-inline my-2 my-lg-0 w-100" do %>
  <div class="form-group">
    <%= text_field_tag(
        :search,
        params[:search],
        placeholder: "Nombre o ingredientes clave",
        class: "form-control my-2"
    ) %>
  </div>

  <%= submit_tag("Buscar", :name => nil, :class => 'btn btn-outline-success my-sm-2 mb-3 ml-2') %>
<% end %>

app/views/partials/_select_category.html.erb
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <label class="input-group-text" for="inputGroupSelect01">Categoria</label>
  </div>
  <select class="custom-select" id="inputGroupSelect01" onchange="follow_link(this)">
    <option value="<%= recipes_path %>">Todas</option>
    <% @categories.each do |category| %>
        <% if current_page?(category_path(category)) %>
           <option  selected value="<%= category_path(category) %>"><%= category.name %></option>
        <% else %>
            <option  value="<%= category_path(category) %>"><%= category.name %></option>
        <% end %>
     <% end %>
  </select>
</div>

app/views/partials/_sidebar.html.erb
<div class="list-group categories">
  <%= link_to_unless_current("Todas", recipes_path, :class => 'list-group-item') do %>
      <%= link_to recipes_path, :class => 'list-group-item active' do %>
        <%= fa_icon 'chevron-left' %> Todas
      <% end %>
  <% end %>
  <% @categories.each do |category| %>
      <%= link_to_unless_current(category.name, category_path(category), :class => 'list-group-item') do %>
          <%= link_to category_path(category), :class => 'list-group-item active'  do %>
            <%= fa_icon 'chevron-left' %> <%= category.name %>
          <% end %>
      <% end %>
    <%# link_to category.name, category_path(category), :class => 'list-group-item' %>
  <% end %>
</div>

app/views/partials/_user_date.html.erb
<small><strong><%= user.username %></strong> on <%= date.in_time_zone('Buenos Aires').to_time.strftime('%B %e at %l:%M %p') %></small>